### ISSUE TITLE
Change codePeriod to projected so that the time limit can be increased

### ISSUE THREAD

**Issue by atodd** [sonata-project/GoogleAuthenticator#135]
## Feature Request

I would like to know if there would be objections to making `codePeriod` a protected variable instead of private.  This would allow for sub-classes to extend the code period.  My use-case is generating a code that can be sent out in email or SMS for users without app access.  Happy to submit a pull request if this seems reasonable.  Thank you.

**Comment by OskarStark** [comment]
Hey @atodd 👋 

To be honest I am not that deep into that lib but maybe its better to keep the variable private and create a new extension point via a setter? Otherwise deprecating such things in the future will be quite hart

WDYT @core23 @kunicmarko20 @greg0ire ?

**Comment by atodd** [comment]
Makes sense to me.

**Comment by core23** [comment]
I'm not sure if anybody of us active contributors is using this bundle...

👍 For a setter, so we are type and null safe

**Comment by greg0ire** [comment]
Please make the setter final and protected.

**Comment by atodd** [comment]
Great I will submit a pull request.  Thanks for the feedback!

**Comment by netniV** [comment]
I created a PR for this which ultimately failed because GoogleAuthenticator CANNOT be inherited (it's marked as final).  Unless we remove the FINAL from GoogleAuthenticaor or make the functions public, this request cannot be implemented.

I've left the PR open, so the change can be modified as desired.  If ultimately, neither way is workable, let me know and I can cancel the PR.

**Comment by bkernal626** [comment]
I could really use an implementation to set a custom codePeriod as well. I have created a PR that addresses this. Feedback is welcome, and I will actively make changes if necessary.
