### ISSUE TITLE
Sensitive information shared with external party

### ISSUE THREAD

**Issue by jan2000** [sonata-project/GoogleAuthenticator#167]
Due to the `GoogleQrUrl::generate` generating a link to api.qrserver.com secrets are shared with the owners of api.qrserver.com.

With this information the owner of api.qrserver.com can generate OTP for each user that sets up 2FA. It also has access to the username and domain depending on implementation (the deprecated `GoogleAuthenticator::getUrl` function encourages these variables to be send).

For a lib that intents to improve security by providing 2FA this should be a no go.

The QR code should be generated locally (either on server or client). If that is not feasible, at least developers using this library should be warned that sensitive information is shared with the owners of api.qrserver.com.

**Comment by core23** [comment]
Can you provide a PR that uses a local QR Code generator? @jan2000

**Comment by jan2000** [comment]
Well I do not have a full PR.

If you want to keep compatibility with direct usage in `<img>` src tags then you have to use a library that generates the qr-code image.

You will have to do something like this in `GoogleQrUrl::generate`:
```php
return 'data:image/png;base64,' . base64_encode(qr_generator_of_your_choice($otpauthString, $size));
```

**Comment by Yarli** [comment]
To be honest I think the QR code generation part is probably best left out of the project to keep it's complexity down since adding QR generation code natively to this project is likely to bulk it up a lot, however perhaps some support for breaking out the data portion of the GoogleQrUrl::generate function.
For example adding a new function called GoogleQRData::generate perhaps, which just returns the data string needed to create the QR code?

I created a workaround for myself, which i'll share below for anyone who's landed here looking for answers.

By simply running the function through parse_str your able to break out the data attribute and then use that for a 3rd party (locally installed) QR generator.
I then simply looped back to the same script in my image tag to go and generate that for me.
When doing the loop back you want to ensure this is going over HTTPS, otherwise your still exposing the secret over plain text. I guess a local loopback in code on the server would be a safer but more complex method.

anyway, this is how I did mine.
```
parse_str(\Sonata\GoogleAuthenticator\GoogleQrUrl::generate($Username, $secret, 'MySite'),$output);
echo "<img src='{$_SERVER['PHP_SELF']}&qr=".urlencode($output['data'])."'>";
```

Depending on what QR generator your using, I used http://phpqrcode.sourceforge.net/, you simply put this at the top of your php file to handle the call back for the image:
```
<?php
if(isset($_GET['qr'])) {
       //Set some expiry on this content to stop browsers caching the image
	header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); // Some time in the past
	header("Cache-Control: no-store, no-cache, must-revalidate"); 
	header("Cache-Control: post-check=0, pre-check=0", false); 
	header("Pragma: no-cache"); 
	header('Content-Type: image/png'); 
	include('path_to_phpqrcode/qrlib.php');
        // outputs image directly into browser, as PNG stream
        QRcode::png($_GET['qr']);
       exit;
}
?>
```
Hope this helps anyone else out who's come here.

**Comment by jan2000** [comment]
And so this issue is swept under the carpet by a bot, sigh... 😞

**Comment by peterhaluska** [comment]
Hi @jan2000, I guess it is fixed in the 2.2.0 version. Isn't it?

**Comment by jan2000** [comment]
@peterhaluska Nope.
The whole point is to never share the secret with an external party, whether this is api.qrserver.com or chart.googleapis.com.

**Comment by peterhaluska** [comment]
Okay, that is not resolved, you are right. 

I thought your main problem was the credibility of the api.qrserver.com service - probably Google Charts is a step forward. :)
